// lib/kenya-locations.ts

export interface SubCounty {
  name: string;
  wards: string[];
}

export interface County {
  name: string;
  code: string;
  subCounties: SubCounty[];
}

export const KENYA_COUNTIES: County[] = [
  {
    name: "Mombasa",
    code: "001",
    subCounties: [
      { name: "Changamwe", wards: ["Port Reitz", "Kipevu", "Airport", "Changamwe", "Chaani"] },
      { name: "Jomvu", wards: ["Jomvu Kuu", "Miritini", "Mikindani"] },
      { name: "Kisauni", wards: ["Mjambere", "Junda", "Bamburi", "Mwakirunge", "Mtopanga", "Magogoni", "Shanzu"] },
      { name: "Nyali", wards: ["Frere Town", "Ziwa la Ng'ombe", "Mkomani", "Kongowea", "Kadzandani"] },
      { name: "Likoni", wards: ["Mtongwe", "Shika Adabu", "Bofu", "Likoni", "Timbwani"] },
      { name: "Mvita", wards: ["Mji Wa Kale/Makadara", "Tudor", "Tononoka", "Shimanzi/Ganjoni", "Majengo"] },
    ],
  },
  {
    name: "Kwale",
    code: "002",
    subCounties: [
      { name: "Matuga", wards: ["Mkongani", "Pongwe/Kikoneni", "Tsimba Golini", "Waa"] },
      { name: "Msambweni", wards: ["Bongwe/Gombato", "Gombato Bongwe", "Ukunda", "Kinondo", "Ramisi"] },
      { name: "Kinango", wards: ["Kasemeni", "Kinango", "Mackinnon Road", "Chengoni/Samburu", "Malalani"] },
      { name: "Lunga Lunga", wards: ["Lunga Lunga", "Vanga", "Pongwe"] },
    ],
  },
  {
    name: "Kilifi",
    code: "003",
    subCounties: [
      { name: "Kilifi North", wards: ["Tezo", "Sokoni", "Kibarani", "Watamu", "Mnarani", "Shimo La Tewa", "Chasimba"] },
      { name: "Kilifi South", wards: ["Junju", "Mwarakaya", "Shimo La Tewa", "Chasimba", "Mtepeni"] },
      { name: "Kaloleni", wards: ["Mariakani", "Kaloleni", "Mwanamwinga", "Jibana"] },
      { name: "Rabai", wards: ["Rabai/Kisurutini", "Ruruma", "Kambe/Ribe", "Mwawesa"] },
      { name: "Ganze", wards: ["Bamba", "Ganze", "Jaribuni", "Sokoke"] },
      { name: "Malindi", wards: ["Malindi Town", "Shella", "Ganda", "Gede", "Jilore", "Kakuyuni", "Madunguni"] },
      { name: "Magarini", wards: ["Gongoni", "Adu", "Garashi", "Marafa", "Magarini", "Sabaki"] },
    ],
  },
  {
    name: "Tana River",
    code: "004",
    subCounties: [
      { name: "Garsen", wards: ["Garsen South", "Garsen Central", "Garsen North", "Garsen West"] },
      { name: "Galole", wards: ["Kinakomba", "Chewani", "Wayu", "Mikinduni"] },
      { name: "Bura", wards: ["Bura", "Chewele", "Sala", "Madogo", "Hiriman/Bangale"] },
    ],
  },
  {
    name: "Lamu",
    code: "005",
    subCounties: [
      { name: "Lamu East", wards: ["Faza", "Kiunga", "Basuba"] },
      { name: "Lamu West", wards: ["Shela", "Mkomani", "Hindi/Mkunumbi", "Hongwe", "Witu", "Bahari"] },
    ],
  },
  {
    name: "Taita Taveta",
    code: "006",
    subCounties: [
      { name: "Taveta", wards: ["Bomeni", "Chala", "Mahoo", "Mboghoni", "Mata"] },
      { name: "Wundanyi", wards: ["Wumingu/Kishushe", "Mbololo", "Werugha", "Wundanyi/Mbale"] },
      { name: "Mwatate", wards: ["Mwatate", "Ronge", "Bura", "Chawia", "Wusi/Kishamba"] },
      { name: "Voi", wards: ["Voi", "Sagalla", "Mbololo", "Kasigau", "Marungu"] },
    ],
  },
  {
    name: "Garissa",
    code: "007",
    subCounties: [
      { name: "Garissa Township", wards: ["Galbet", "Waberi", "Township", "Iftin"] },
      { name: "Balambala", wards: ["Balambala", "Saka", "Sankuri", "Dadaab"] },
      { name: "Lagdera", wards: ["Benane", "Goreale", "Sabena", "Maalimin", "Modogashe"] },
      { name: "Dadaab", wards: ["Dadaab", "Labasigale", "Dertu", "Abakaile"] },
      { name: "Fafi", wards: ["Fafi", "Bura", "Dekaharia", "Nanighi", "Jarajila"] },
      { name: "Ijara", wards: ["Ijara", "Sangailu", "Masalani", "Hulugho"] },
    ],
  },
  {
    name: "Wajir",
    code: "008",
    subCounties: [
      { name: "Wajir North", wards: ["Batalu", "Danaba", "Gurar", "Malkagufu"] },
      { name: "Wajir East", wards: ["Barwaqo", "Khorof/Harar", "Elben", "Wagberi", "Tarbaj", "Wajir Bor"] },
      { name: "Tarbaj", wards: ["Tarbaj", "Wajir South", "Sarman", "Kutulo"] },
      { name: "Wajir West", wards: ["Ademasajida", "Ganyure/Wagalla", "Hadado/Athibohol", "Habaswein"] },
      { name: "Eldas", wards: ["Della", "Lakoley South/Basir", "Elnur/Tula Tula", "Habaswein"] },
      { name: "Wajir South", wards: ["Ijara", "Diif", "Lagboghol South", "Burder"] },
    ],
  },
  {
    name: "Mandera",
    code: "009",
    subCounties: [
      { name: "Mandera West", wards: ["Takaba South", "Gither", "Takaba", "Dandu"] },
      { name: "Banissa", wards: ["Banissa", "Derkhale", "Malkamari"] },
      { name: "Mandera North", wards: ["Ashabito", "Libehia", "Rhamu", "Rhamu Dimtu"] },
      { name: "Mandera South", wards: ["Elwak South", "Elwak North", "Wargadud", "Kutulo"] },
      { name: "Mandera East", wards: ["Khalalio", "Neboi", "Fino", "Kutulo"] },
      { name: "Lafey", wards: ["Lafey", "Wayu", "Fino", "Della"] },
    ],
  },
  {
    name: "Marsabit",
    code: "010",
    subCounties: [
      { name: "Moyale", wards: ["Golbo", "Moyale Township", "Obbu", "Sololo", "Uran"] },
      { name: "North Horr", wards: ["Dukana", "Maikona", "North Horr", "Turbi"] },
      { name: "Saku", wards: ["Marsabit Central", "Marsabit South", "Karare", "Sagante/Jaldesa"] },
      { name: "Laisamis", wards: ["Laisamis", "Korr/Ngurunit", "Logologo", "Ngurunet"] },
    ],
  },
  {
    name: "Isiolo",
    code: "011",
    subCounties: [
      { name: "Isiolo North", wards: ["Bulla Pesa", "Chari", "Cherab", "Wabera"] },
      { name: "Isiolo South", wards: ["Kinna", "Garba Tula", "Oldonyiro"] },
      { name: "Merti", wards: ["Cherab", "Chari", "Ngare Mara"] },
    ],
  },
  {
    name: "Meru",
    code: "012",
    subCounties: [
      { name: "Imenti North", wards: ["Nyaki West", "Nyaki East", "Municipality", "Abogeta West", "Abogeta East"] },
      { name: "Imenti South", wards: ["Igoji East", "Igoji West", "Mitunguu", "Abothuguchi Central", "Abothuguchi West"] },
      { name: "Imenti Central", wards: ["Abogeta West", "Kiagu", "Mitunguu", "Athiru Gaiti", "Ruiri/Rwarera"] },
      { name: "Buuri", wards: ["Timau", "Kisima", "Kibirichia", "Ruiri/Rwarera", "Kiirua/Naari"] },
      { name: "Igembe South", wards: ["Muthara", "Kangeta", "Athiru Ruujine", "Akithi", "Nkondi"] },
      { name: "Igembe Central", wards: ["Igembe Central", "Athiru Gaiti", "Akirang'ondu", "Akachiu"] },
      { name: "Igembe North", wards: ["Igembe North", "Antubochiu", "Ntunene", "Naathu"] },
      { name: "Tigania West", wards: ["Kianjai", "Nkomo", "Akithii", "Mbeu", "Mikinduri"] },
      { name: "Tigania East", wards: ["Muthara", "Mbeu", "Amwathi", "Karama", "Thangatha"] },
    ],
  },
  {
    name: "Tharaka Nithi",
    code: "013",
    subCounties: [
      { name: "Tharaka North", wards: ["Gatunga", "Mukothima"] },
      { name: "Tharaka South", wards: ["Marimanti", "Chiakariga", "Nkondi"] },
      { name: "Chuka/Igambang'ombe", wards: ["Karingani", "Mariani", "Mugwe", "Magumoni", "Giaki"] },
      { name: "Maara", wards: ["Chogoria", "Ganga", "Mitheru", "Magutuni", "Muthambi"] },
      { name: "Meru South", wards: ["Abothuguchi Central", "Abothuguchi West", "Akithi", "Kiagu"] },
    ],
  },
  {
    name: "Embu",
    code: "014",
    subCounties: [
      { name: "Manyatta", wards: ["Kithimu", "Nginda", "Gaturi South", "Evurore", "Mbeti North"] },
      { name: "Runyenjes", wards: ["Kagaari North", "Kagaari South", "Kyeni North", "Kyeni South", "Gaturi South"] },
      { name: "Mbeere South", wards: ["Mavuria", "Kiritiri", "Makima", "Mbeti South", "Makima"] },
      { name: "Mbeere North", wards: ["Muminji", "Evurore", "Mbeti North"] },
    ],
  },
  {
    name: "Kitui",
    code: "015",
    subCounties: [
      { name: "Mwingi North", wards: ["Kyuso", "Mumoni", "Tseikuru", "Mutitu/Kaliku", "Ngomeni"] },
      { name: "Mwingi West", wards: ["Migwani", "Kiomo/Kyethani", "Kyome/Thaana", "Ngutani", "Waita"] },
      { name: "Mwingi Central", wards: ["Central", "Kivou", "Ngomano", "Mui", "Waita"] },
      { name: "Kitui West", wards: ["Kauwi", "Matinyani", "Kwa Mutonga/Kithumula", "Kwavonza/Yatta"] },
      { name: "Kitui Rural", wards: ["Kisasi", "Mbitini", "Chuluni", "Ikutha"] },
      { name: "Kitui Central", wards: ["Township", "Miambani", "Mulango", "Kyangwithya West", "Kyangwithya East"] },
      { name: "Kitui East", wards: ["Endau/Malalani", "Mutito/Kaliku", "Ikanga/Kyatune", "Zombe/Mwitika"] },
      { name: "Kitui South", wards: ["Ikanga", "Athi", "Mutomo", "Ikutha", "Kanziko/Mavindu"] },
    ],
  },
  {
    name: "Machakos",
    code: "016",
    subCounties: [
      { name: "Masinga", wards: ["Kivaa", "Masinga Central", "Ekalakala", "Muthesya", "Ndithini"] },
      { name: "Yatta", wards: ["Kithimani", "Ikombe", "Matungulu North", "Kola", "Katangi"] },
      { name: "Kangundo", wards: ["Kangundo North", "Kangundo Central", "Kangundo East", "Kangundo West"] },
      { name: "Matungulu", wards: ["Tala", "Matungulu North", "Matungulu West", "Matungulu East", "Kyeleni"] },
      { name: "Kathiani", wards: ["Kathiani", "Mitaboni", "Ikalaasa", "Kathiani Central"] },
      { name: "Mavoko", wards: ["Syokimau/Mulolongo", "Athi River", "Kinanie", "Muthwani"] },
      { name: "Machakos Town", wards: ["Mumbuni North", "Muvuti/Kiima-Kimwe", "Machakos Central", "Kalama", "Kola"] },
      { name: "Mwala", wards: ["Mbiuni", "Wamunyu", "Muthetheni", "Makutano/Mwala"] },
    ],
  },
  {
    name: "Makueni",
    code: "017",
    subCounties: [
      { name: "Makueni", wards: ["Mbitini", "Wote", "Mavindini", "Kitise/Kithuki", "Makindu"] },
      { name: "Kibwezi West", wards: ["Emali/Mulala", "Nguumo", "Kiima Kiu/Kalanzoni"] },
      { name: "Kibwezi East", wards: ["Masongaleni", "Mtito Andei", "Thange"] },
      { name: "Kilome", wards: ["Kilome", "Kasikeu", "Mukaa", "Kiima Kiu"] },
      { name: "Kaiti", wards: ["Kilungu", "Kee", "Kisau/Kiteta"] },
      { name: "Mbooni", wards: ["Kalawa", "Mbumbuni", "Kithungo/Kitundu", "Waia/Kako", "Kiteta", "Kisau"] },
    ],
  },
  {
    name: "Nyandarua",
    code: "018",
    subCounties: [
      { name: "Kinangop", wards: ["Murungaru", "Gathara", "Githabai", "North Kinangop", "Nyakio"] },
      { name: "Kipipiri", wards: ["Wanjohi", "Kipipiri", "Geta", "Githioro"] },
      { name: "Ol Kalou", wards: ["Mirangine", "Karau", "Rurii", "Gathanji"] },
      { name: "Ol Joro Orok", wards: ["Gathanji", "Gatimu", "Weru", "Charagita"] },
      { name: "Ndaragwa", wards: ["Leshau/Pondo", "Kiriita", "Central", "Shamata"] },
    ],
  },
  {
    name: "Nyeri",
    code: "019",
    subCounties: [
      { name: "Tetu", wards: ["Dedan Kimathi", "Wamagana", "Aguthi/Gaaki"] },
      { name: "Kieni East", wards: ["Gatarakwa", "Thegu River", "Naromoru/Kiamathaga", "Kabaru"] },
      { name: "Kieni West", wards: ["Mugunda", "Gakawa", "Mweiga", "Naromoru/Kiamathaga"] },
      { name: "Mathira East", wards: ["Magutu", "Iriaini", "Konyu", "Ruguru"] },
      { name: "Mathira West", wards: ["Magutu", "Iria-ini", "Mwiyogo/Endarasha", "Karatina Town"] },
      { name: "Othaya", wards: ["Mahiga", "Iria-ini", "Karima", "Chinga"] },
      { name: "Mukurweini", wards: ["Gikondi", "Mukurwe-ini West", "Mukurwe-ini Central"] },
      { name: "Nyeri Town", wards: ["Ruring'u", "Kamakwa/Mukaro", "Gatitu/Muruguru", "Rware", "Ruringu"] },
    ],
  },
  {
    name: "Kirinyaga",
    code: "020",
    subCounties: [
      { name: "Mwea", wards: ["Mutithi", "Kangai", "Thiba", "Wamumu", "Nyangati", "Murinduko"] },
      { name: "Gichugu", wards: ["Baragwi", "Njukiini", "Ngariama", "Karumandi"] },
      { name: "Ndia", wards: ["Kariti", "Mukure", "Kiine"] },
      { name: "Kirinyaga Central", wards: ["Mutira", "Kanyekiini", "Kerugoya", "Inoi"] },
    ],
  },
  {
    name: "Murang'a",
    code: "021",
    subCounties: [
      { name: "Kangema", wards: ["Kagumo", "Kangema", "Muguru", "Rwathia"] },
      { name: "Mathioya", wards: ["Kiru", "Kamacharia", "Gitugi", "Kamumu"] },
      { name: "Kiharu", wards: ["Wangu", "Mugoiri", "Mbiri", "Township", "Murarandia"] },
      { name: "Kigumo", wards: ["Kinyona", "Kigumo", "Kahumbu", "Kangari"] },
      { name: "Maragwa", wards: ["Makuyu", "Kambiti", "Kamahuha", "Ichagaki", "Kimorori/Wempa"] },
      { name: "Kandara", wards: ["Kagundu-ini", "Gaichanjiru", "Ithanga", "Ruchu", "Nginda"] },
      { name: "Gatanga", wards: ["Kariara", "Kakuzi/Mitubiri", "Kihumbu-ini", "Mukarara", "Gatanga"] },
    ],
  },
  {
    name: "Kiambu",
    code: "022",
    subCounties: [
      { name: "Gatundu South", wards: ["Kiamwangi", "Kiganjo", "Ndarugu", "Ngenda"] },
      { name: "Gatundu North", wards: ["Gituamba", "Githobokoni", "Chania", "Mang'u"] },
      { name: "Juja", wards: ["Kalimoni", "Witeithie", "Theta", "Juja", "Murera"] },
      { name: "Thika Town", wards: ["Township", "Kamenu", "Hospital", "Gatuanyaga", "Ngoliba"] },
      { name: "Ruiru", wards: ["Gitothua", "Biashara", "Gatongora", "Kahawa Sukari", "Kahawa Wendani", "Kiuu", "Mwiki", "Mwihoko"] },
      { name: "Githunguri", wards: ["Githunguri", "Githiga", "Ikinu", "Ngewa", "Komothai"] },
      { name: "Kiambu", wards: ["Township", "Ndumberi", "Riabai", "Tinganga"] },
      { name: "Kiambaa", wards: ["Kihara", "Cianda", "Karuri", "Ndenderu", "Muchatha"] },
      { name: "Kabete", wards: ["Gitaru", "Muguga", "Nyadhuna", "Kabete", "Uthiru"] },
      { name: "Kikuyu", wards: ["Karai", "Nachu", "Sigona", "Kikuyu", "Kinoo"] },
      { name: "Limuru", wards: ["Bibirioni", "Limuru Central", "Ndeiya", "Limuru East", "Ngecha Tigoni"] },
      { name: "Lari", wards: ["Kinale", "Kijabe", "Nyanduma", "Kamburu", "Lari/Kirenga"] },
    ],
  },
  {
    name: "Turkana",
    code: "023",
    subCounties: [
      { name: "Turkana North", wards: ["Kaeris", "Lake Zone", "Nachukui"] },
      { name: "Turkana West", wards: ["Kakuma", "Lokichoggio", "Songot", "Nanaam"] },
      { name: "Turkana Central", wards: ["Kerio Delta", "Kalokol", "Lodwar Township", "Kanamkemer"] },
      { name: "Loima", wards: ["Kotaruk/Lobei", "Turkwel", "Loima", "Lokiriama/Lorengippi"] },
      { name: "Turkana South", wards: ["Katilu", "Lobokat", "Kalapata", "Lokichar"] },
      { name: "Turkana East", wards: ["Kapedo/Napeitom", "Katilia", "Lokori/Kochodin"] },
    ],
  },
  {
    name: "West Pokot",
    code: "024",
    subCounties: [
      { name: "Kapenguria", wards: ["Riwo", "Kapenguria", "Mnagei", "Siyoi"] },
      { name: "Sigor", wards: ["Sekerr", "Masool", "Lomut", "Weiwei"] },
      { name: "Kacheliba", wards: ["Suam", "Kodich", "Kasei", "Kapchok"] },
      { name: "Pokot South", wards: ["Chepareria", "Batei", "Lelan", "Tapach"] },
    ],
  },
  {
    name: "Samburu",
    code: "025",
    subCounties: [
      { name: "Samburu North", wards: ["El-Barta", "Nachola", "Ndoto", "Ngutuk Ongiron", "Baawa"] },
      { name: "Samburu East", wards: ["Wamba West", "Wamba East", "Wamba North", "Waso"] },
      { name: "Samburu Central", wards: ["Lodokejek", "Suguta Marmar", "Maralal", "Loosuk", "Poro"] },
    ],
  },
  {
    name: "Trans Nzoia",
    code: "026",
    subCounties: [
      { name: "Kwanza", wards: ["Kapomboi", "Kwanza", "Keiyo"] },
      { name: "Endebess", wards: ["Chepchoina", "Endebess", "Matumbei"] },
      { name: "Saboti", wards: ["Saboti", "Machewa", "Tuwani", "Kinyoro", "Matisi"] },
      { name: "Kiminini", wards: ["Kiminini", "Waitaluk", "Sirende", "Nabiswa", "Sikhendu"] },
      { name: "Cherangany", wards: ["Sinyerere", "Makutano", "Kaplamai", "Motosiet", "Cherangany/Suwerwa", "Chepsiro/Kiptoyo", "Sitatunga"] },
    ],
  },

  
  // Complete Uasin Gishu (027) and add counties 028-047
// Add this to your existing KENYA_COUNTIES array after Samburu and Trans Nzoia

  {
    name: "Uasin Gishu",
    code: "027",
    subCounties: [
      { name: "Soy", wards: ["Soy", "Kuinet/Kapsuswa", "Kaptagat", "Ziwa", "Cheptiret/Kipchamo", "Megun", "Segero/Barsombe"] },
      { name: "Turbo", wards: ["Huruma", "Kapsoya", "Tapsagoi", "Kiplombe", "Kapsaos", "Kamagut"] },
      { name: "Moiben", wards: ["Kimumu", "Moiben", "Tembelio"] },
      { name: "Ainabkoi", wards: ["Olare", "Ainabkoi/Olare", "Kapseret"] },
      { name: "Kapseret", wards: ["Simat/Kapseret", "Kipkenyo", "Ngenyilel", "Megun", "Langas"] },
      { name: "Kesses", wards: ["Racecourse", "Chepkoilel", "Tulwet/Chuiyat", "Tarakwa", "Kesses"] },
    ],
  },
  {
    name: "Elgeyo Marakwet",
    code: "028",
    subCounties: [
      { name: "Marakwet East", wards: ["Kapyego", "Sambirir", "Endo", "Embobut/Embulot"] },
      { name: "Marakwet West", wards: ["Lelan", "Sengwer", "Cherang'any/Chebororwa", "Moiben/Kuserwo", "Arror"] },
      { name: "Keiyo North", wards: ["Emsoo", "Kamariny", "Kapchemutwa", "Tambach"] },
      { name: "Keiyo South", wards: ["Soy North", "Soy South", "Kabiemit", "Metkei", "Chepkorio"] },
    ],
  },
  {
    name: "Nandi",
    code: "029",
    subCounties: [
      { name: "Tinderet", wards: ["Songhor/Soba", "Tinderet", "Chemelil/Chemase", "Kapsimotwo", "Kiptagen"] },
      { name: "Aldai", wards: ["Kabisaga", "Ndalat", "Kemeloi-Maraba", "Kobujoi", "Terik", "Kaptumo-Kaboi"] },
      { name: "Nandi Hills", wards: ["Nandi Hills", "Chepkunyuk", "Ol'lessos", "Kapchorua"] },
      { name: "Chesumei", wards: ["Chemundu/Kapng'etuny", "Kosirai", "Lelmokwo/Ngechek", "Kaptel/Kamoiywo", "Kiptuya"] },
      { name: "Emgwen", wards: ["Chepkumia", "Kapkangani", "Kapsabet", "Kilibwoni"] },
      { name: "Mosop", wards: ["Kabwareng", "Ndurio/Equator", "Chepterwai", "Kipkaren", "Kurgung/Surungai", "Kabiyet", "Mosop"] },
    ],
  },
  {
    name: "Baringo",
    code: "030",
    subCounties: [
      { name: "Baringo North", wards: ["Barwessa", "Kabartonjo", "Saimo/Kipsaraman", "Saimo/Soi", "Bartabwa"] },
      { name: "Baringo Central", wards: ["Kabarnet", "Sacho", "Tenges", "Ewalel Chapchap", "Kapropita"] },
      { name: "Baringo South", wards: ["Marigat", "Ilchamus", "Mochongoi", "Mukutan"] },
      { name: "Eldama Ravine", wards: ["Lembus", "Lembus Kwen", "Ravine", "Koibatek"] },
      { name: "Mogotio", wards: ["Mogotio", "Emining", "Kisanana"] },
      { name: "Tiaty", wards: ["Tirioko", "Kolowa", "Ribkwo", "Silale", "Loiyamorock", "Tangulbei/Korossi", "Churo/Amaya"] },
    ],
  },
  {
    name: "Laikipia",
    code: "031",
    subCounties: [
      { name: "Laikipia West", wards: ["Olmoran", "Rumuruti Township", "Marmanet", "Igwamiti", "Githiga"] },
      { name: "Laikipia East", wards: ["Nanyuki", "Umande", "Thingithu", "Ngobit", "Tigithi"] },
      { name: "Laikipia North", wards: ["Sosian", "Segera", "Mugogodo West", "Mugogodo East"] },
    ],
  },
  {
    name: "Nakuru",
    code: "032",
    subCounties: [
      { name: "Nakuru Town East", wards: ["Biashara", "Kivumbini", "Flamingo", "Menengai West", "Nakuru East"] },
      { name: "Nakuru Town West", wards: ["Kapkures", "Rhoda", "London", "Kaptembwa", "Shabaab"] },
      { name: "Gilgil", wards: ["Gilgil", "Elementaita", "Mbaruk/Eburu", "Malewa West", "Nyahururu"] },
      { name: "Naivasha", wards: ["Hells Gate", "Lake View", "Mai Mahiu", "Naivasha East", "Viwandani"] },
      { name: "Molo", wards: ["Mariashoni", "Elburgon", "Molo", "Turi"] },
      { name: "Njoro", wards: ["Mau Narok", "Mauche", "Kihingo", "Nessuit", "Lare", "Njoro"] },
      { name: "Rongai", wards: ["Menengai", "Soin", "Visoi", "Mosop", "Solai"] },
      { name: "Subukia", wards: ["Subukia", "Waseges", "Kabazi"] },
      { name: "Bahati", wards: ["Lanet/Umoja", "Bahati", "Dundori", "Kabatini", "Kiamaina"] },
      { name: "Kuresoi South", wards: ["Amalo", "Keringet", "Kiptagich", "Tinet"] },
      { name: "Kuresoi North", wards: ["Kiptororo", "Nyota", "Sirikwa", "Kamara"] },
    ],
  },
  {
    name: "Narok",
    code: "033",
    subCounties: [
      { name: "Narok North", wards: ["Olokurto", "Narok Town", "Nkareta", "Olorropil", "Melili"] },
      { name: "Narok South", wards: ["Majimoto/Naroosura", "Ololulung'a", "Melelo", "Loita", "Sogoo", "Sagamian"] },
      { name: "Narok East", wards: ["Mosiro", "Ildamat", "Keekonyokie", "Suswa"] },
      { name: "Narok West", wards: ["Ilmotiok", "Mara", "Siana", "Naikarra"] },
      { name: "Transmara West", wards: ["Ilkerin", "Ololmasani", "Mogondo", "Keyian", "Angata Barikoi", "Kimintet"] },
      { name: "Transmara East", wards: ["Ololaimutiek", "Kapsasian", "Shankoe", "Pirrar", "Riogo"] },
    ],
  },
  {
    name: "Kajiado",
    code: "034",
    subCounties: [
      { name: "Kajiado North", wards: ["Ongata Rongai", "Nkaimurunya", "Oloolua", "Ngong", "Mosiro"] },
      { name: "Kajiado Central", wards: ["Purko", "Ildamat", "Dalalekutuk", "Matapato North", "Matapato South"] },
      { name: "Kajiado East", wards: ["Kaputiei North", "Kitengela", "Oloosirkon/Sholinke", "Kenyawa-Poka", "Imaroro"] },
      { name: "Kajiado West", wards: ["Keekonyokie", "Iloodokilani", "Magadi", "Ewuaso Oonkidong'i", "Mosiro"] },
      { name: "Kajiado South", wards: ["Entonet/Lenkism", "Mbirikani/Eselenkei", "Kuku", "Rombo", "Kimana"] },
    ],
  },
  {
    name: "Kericho",
    code: "035",
    subCounties: [
      { name: "Kipkelion East", wards: ["Tendeno/Sorget", "Chepseon", "Kamasian", "Kipkelion"] },
      { name: "Kipkelion West", wards: ["Kunyak", "Kamasian", "Kipkelion", "Chilchila"] },
      { name: "Ainamoi", wards: ["Ainamoi", "Kapkugerwet", "Kapsoit", "Kipchebor", "Kipchimchim", "Kapsuser"] },
      { name: "Bureti", wards: ["Litein", "Cheplanget", "Cheboin", "Chemosot", "Kisiara", "Tebesonik"] },
      { name: "Belgut", wards: ["Waldai", "Kabianga", "Cheptororiet/Seretut", "Chaik", "Kapsuser"] },
      { name: "Sigowet/Soin", wards: ["Sigowet", "Kaplelartet", "Soliat", "Soin"] },
    ],
  },
  {
    name: "Bomet",
    code: "036",
    subCounties: [
      { name: "Sotik", wards: ["Ndanai/Abosi", "Chemagel", "Kapletundo", "Rongena", "Kipsonoi"] },
      { name: "Chepalungu", wards: ["Kong'asis", "Nyangores", "Sigor", "Chebunyo", "Siongiroi"] },
      { name: "Bomet East", wards: ["Merigi", "Kembu", "Longisa", "Kipreres", "Chemaner"] },
      { name: "Bomet Central", wards: ["Silibwet Township", "Ndaraweta", "Singorwet", "Chesoen", "Mutarakwa"] },
      { name: "Konoin", wards: ["Kimulot", "Mogogosiek", "Boito", "Embomos", "Chepchabas"] },
    ],
  },
  {
    name: "Kakamega",
    code: "037",
    subCounties: [
      { name: "Lugari", wards: ["Lugari", "Lumakanda", "Chekalini", "Chevaywa", "Lwandeti", "Mautuma"] },
      { name: "Likuyani", wards: ["Likuyani", "Sango", "Kongoni", "Nzoia", "Sinoko"] },
      { name: "Malava", wards: ["West Kabras", "Chemuche", "East Kabras", "Butali/Chegulo", "Manda-Shivanga", "Shirugu-Mugai", "South Kabras"] },
      { name: "Lurambi", wards: ["Butsotso East", "Butsotso South", "Butsotso Central", "Sheywe", "Mahiakalo", "Shirere"] },
      { name: "Navakholo", wards: ["Ingostse-Mathia", "Shinoyi-Shikomari-Esumeyia", "Bunyala West", "Bunyala East", "Bunyala Central"] },
      { name: "Mumias West", wards: ["Mumias Central", "Mumias North", "Etenje", "Musanda", "Malaha/Isongo/Makunga", "Kholera"] },
      { name: "Mumias East", wards: ["Lubao", "Lusheya/Lubinu", "Mayoni", "Ekero/Mukhonje"] },
      { name: "Matungu", wards: ["Koyonzo", "Kholera", "Khalaba", "Mayoni", "Namamali"] },
      { name: "Butere", wards: ["Marama West", "Marama Central", "Marenyo-Shianda", "Marama North", "Marama South"] },
      { name: "Khwisero", wards: ["Kisa North", "Kisa East", "Kisa West", "Kisa Central"] },
      { name: "Shinyalu", wards: ["Isukha North", "Murhanda", "Isukha Central", "Isukha South", "Isukha East", "Isukha West"] },
      { name: "Ikolomani", wards: ["Idakho South", "Idakho East", "Idakho North", "Idakho Central"] },
    ],
  },
  {
    name: "Vihiga",
    code: "038",
    subCounties: [
      { name: "Vihiga", wards: ["Lugaga-Wamuluma", "South Maragoli", "Central Maragoli", "Mungoma"] },
      { name: "Sabatia", wards: ["Tambua", "Chavakali", "North Maragoli", "Wodanga", "Busali", "Lyaduywa/Izava"] },
      { name: "Hamisi", wards: ["Shiru", "Muhudu", "Banja", "Tambulilwa", "Jepkoyai"] },
      { name: "Luanda", wards: ["Luanda Township", "Wemilabi", "Mwibona", "Luanda South", "Emabungo"] },
      { name: "Emuhaya", wards: ["North East Bunyore", "Central Bunyore", "West Bunyore"] },
    ],
  },
  {
    name: "Bungoma",
    code: "039",
    subCounties: [
      { name: "Mt. Elgon", wards: ["Cheptais", "Chesikaki", "Chepyuk", "Kapkateny", "Kaptama", "Elgon"] },
      { name: "Sirisia", wards: ["Namwela", "Malakisi/South Kulisiru", "Lwandanyi", "Sirisia"] },
      { name: "Kabuchai", wards: ["Kabuchai/Chwele", "Nalondo", "Bwake/Luuya", "Mukuyuni"] },
      { name: "Bumula", wards: ["Bumula", "Khasoko", "Kabula", "Kimaeti", "South Bukusu", "Siboti"] },
      { name: "Kanduyi", wards: ["Bukembe West", "Bukembe East", "Township", "Khalaba", "Musikoma", "East Sang'alo", "Tuuti/Marakaru"] },
      { name: "Webuye East", wards: ["Ndivisi", "Maraka", "Mihuu", "Ndalu/Tabani"] },
      { name: "Webuye West", wards: ["Sitikho", "Matulo", "Bokoli"] },
      { name: "Kimilili", wards: ["Kimilili", "Maeni", "Kamukuywa"] },
      { name: "Tongaren", wards: ["Tongaren", "Naitiri/Kabuyefwe", "Mbakalo", "Ndalu/Soysambu", "Milima"] },
    ],
  },
  {
    name: "Busia",
    code: "040",
    subCounties: [
      { name: "Teso North", wards: ["Malaba North", "Malaba South", "Ang'urai North", "Ang'urai South", "Ang'urai East"] },
      { name: "Teso South", wards: ["Ang'orom", "Chakol South", "Chakol North", "Amukura West", "Amukura East"] },
      { name: "Nambale", wards: ["Nambale Township", "Bukhayo North/Waltsi", "Bukhayo East", "Bukhayo Central"] },
      { name: "Matayos", wards: ["Burumba", "Marachi West", "Marachi Central", "Marachi East", "Marachi North"] },
      { name: "Butula", wards: ["Marachi Central", "Kingandole", "Marachi East", "Marachi North", "Elugulu"] },
      { name: "Funyula", wards: ["Namboboto Nambuku", "Ageng'a Nanguba", "Bwiri", "Nambale"] },
      { name: "Budalangi", wards: ["Bunyala Central", "Bunyala South", "Bunyala North", "Bunyala West"] },
    ],
  },
  {
    name: "Siaya",
    code: "041",
    subCounties: [
      { name: "Ugenya", wards: ["East Ugenya", "Ukwala", "North Ugenya", "West Ugenya"] },
      { name: "Ugunja", wards: ["Sidindi", "Sigomre", "Ugunja"] },
      { name: "Alego Usonga", wards: ["Usonga", "West Alego", "Central Alego", "Siaya Township", "North Alego", "South East Alego"] },
      { name: "Gem", wards: ["North Gem", "West Gem", "Central Gem", "Yala Township", "East Gem", "South Gem"] },
      { name: "Bondo", wards: ["West Yimbo", "Central Sakwa", "South Sakwa", "Yimbo East", "West Sakwa", "North Sakwa"] },
      { name: "Rarieda", wards: ["West Asembo", "North Uyoma", "South Uyoma", "West Uyoma", "East Asembo", "North Asembo"] },
    ],
  },
  {
    name: "Kisumu",
    code: "042",
    subCounties: [
      { name: "Kisumu East", wards: ["Kajulu", "Kolwa East", "Manyatta B", "Nyalenda A"] },
      { name: "Kisumu West", wards: ["North West Kisumu", "Central Kisumu", "South West Kisumu", "Kisumu North"] },
      { name: "Kisumu Central", wards: ["Market Milimani", "Railways", "Migosi", "Shaurimoyo Kaloleni", "Nyalenda B"] },
      { name: "Seme", wards: ["North Seme", "Central Seme", "East Seme", "West Seme"] },
      { name: "Nyando", wards: ["Lower Nyakach", "Nyakach", "Central Nyakach", "South West Nyakach", "Kabonyo Kanyagwal"] },
      { name: "Muhoroni", wards: ["Miwani", "Ombeyi", "Masogo/Nyang'oma", "Chemelil"] },
      { name: "Nyakach", wards: ["South West Nyakach", "North Nyakach", "Central Nyakach", "West Nyakach"] },
    ],
  },
  {
    name: "Homa Bay",
    code: "043",
    subCounties: [
      { name: "Kasipul", wards: ["West Kasipul", "South Kasipul", "Central Kasipul", "East Kamagak", "West Kamagak"] },
      { name: "Kabondo Kasipul", wards: ["Kabondo East", "Kabondo West", "Kokwanyo/Kakelo", "Kojwach"] },
      { name: "Karachuonyo", wards: ["West Karachuonyo", "North Karachuonyo", "Central", "Kanyaluo", "Kibiri", "Wangchieng", "Kendu Bay Town"] },
      { name: "Rangwe", wards: ["West Gem", "East Gem", "Kagan", "Kochia"] },
      { name: "Homa Bay Town", wards: ["Homa Bay Central", "Homa Bay Arujo", "Homa Bay West", "Homa Bay East"] },
      { name: "Ndhiwa", wards: ["Kwabwai", "Kanyadoto", "Kanyikela", "North Kabuoch", "Central Kanyamwa", "West Kanyamwa", "South Kanyamwa", "East Kanyamwa"] },
      { name: "Suba North", wards: ["Mfangano Island", "Rusinga Island", "Kasgunga", "Gembe", "Lambwe"] },
      { name: "Suba South", wards: ["Gwassi South", "Gwassi North", "Kaksingri West", "Ruma-Kaksingri East"] },
    ],
  },
  {
    name: "Migori",
    code: "044",
    subCounties: [
      { name: "Rongo", wards: ["North Kamagambo", "Central Kamagambo", "East Kamagambo", "South Kamagambo"] },
      { name: "Awendo", wards: ["North Sakwa", "South Sakwa", "West Sakwa", "Central Sakwa"] },
      { name: "Suna East", wards: ["God Jope", "Suna Central", "Kakrao", "Kwa"] },
      { name: "Suna West", wards: ["Wiga", "Wasweta II", "Ragana-Oruba", "Wasimbete"] },
      { name: "Uriri", wards: ["West Kanyamkago", "North Kanyamkago", "Central Kanyamkago", "South Kanyamkago", "East Kanyamkago"] },
      { name: "Nyatike", wards: ["Kachieng'", "Kanyasa", "North Kadem", "Macalder/Kanyarwanda", "Kaler", "Got Kachola", "Muhuru"] },
      { name: "Kuria West", wards: ["Bukira East", "Bukira Central/Ikerege", "Isibania", "Makerero", "Masaba", "Tagare", "Nyabasi East", "Nyabasi West"] },
      { name: "Kuria East", wards: ["Kegonga", "Ntimaru West", "Ntimaru East", "Nyabasi Central", "Gokeharaka/Getambwega", "Ntimaru"] },
    ],
  },
  {
    name: "Kisii",
    code: "045",
    subCounties: [
      { name: "Bonchari", wards: ["Tabaka", "Bomariba", "Bogiakumu", "Bomorenda"] },
      { name: "South Mugirango", wards: ["Tabaka", "Boikanga", "Bogetenga", "Borabu/Chitago", "Moticho", "Getenga"] },
      { name: "Bomachoge Borabu", wards: ["Bombaba Borabu", "Bomariba", "Bosoti/Sengera", "Bokimonge", "Magenche"] },
      { name: "Bobasi", wards: ["Masige West", "Masige East", "Basi Central", "Nyacheki", "Bassi Bogetaorio", "Bobasi Chache", "Sameta/Mokwerero", "Bobasi/Boitangare"] },
      { name: "Bomachoge Chache", wards: ["Majoge Basi", "Boochi/Tendere", "Bosoti/Sengera"] },
      { name: "Nyaribari Masaba", wards: ["Nyamasibi", "Masimba", "Gesusu", "Kiamokama"] },
      { name: "Nyaribari Chache", wards: ["Bobaracho", "Kisii Central", "Keumbu", "Kiogoro", "Birongo", "Ibeno"] },
      { name: "Kitutu Chache North", wards: ["Monyerero", "Sensi", "Marani", "Kegati"] },
      { name: "Kitutu Chache South", wards: ["Bogusero", "Bogeka", "Nyakoe", "Kitutu Central", "Nyatieko"] },
    ],
  },
  {
    name: "Nyamira",
    code: "046",
    subCounties: [
      { name: "Kitutu Masaba", wards: ["Rigoma", "Gachuba", "Kemera", "Magombo", "Manga", "Gesima"] },
      { name: "West Mugirango", wards: ["Kebate", "Bogichora", "Bosamaro", "Bonyamatuta", "Township"] },
      { name: "North Mugirango", wards: ["Itibo", "Bomwagamo", "Bokeira", "Magwagwa", "Ekerenyo"] },
      { name: "Borabu", wards: ["Mekenene", "Nyansiongo", "Esise", "Kiabonyoru"] },
      { name: "Manga", wards: ["Manga", "Matutu", "Nyamaiya", "Gesima"] },
    ],
  },
  {
    name: "Nairobi",
    code: "047",
    subCounties: [
      { name: "Westlands", wards: ["Kitisuru", "Parklands/Highridge", "Karura", "Kangemi", "Mountain View"] },
      { name: "Dagoretti North", wards: ["Kilimani", "Kawangware", "Gatina", "Kileleshwa", "Kabiro"] },
      { name: "Dagoretti South", wards: ["Mutuini", "Ngando", "Riruta", "Uthiru/Ruthimitu", "Waithaka"] },
      { name: "Langata", wards: ["Karen", "Nairobi West", "Mugumu-ini", "South C", "Nyayo Highrise"] },
      { name: "Kibra", wards: ["Laini Saba", "Lindi", "Makina", "Woodley/Kenyatta Golf Course", "Sarang'ombe"] },
      { name: "Roysambu", wards: ["Githurai", "Kahawa West", "Zimmerman", "Roysambu", "Kahawa"] },
      { name: "Kasarani", wards: ["Clay City", "Mwiki", "Kasarani", "Njiru", "Ruai"] },
      { name: "Ruaraka", wards: ["Babadogo", "Utalii", "Mathare North", "Lucky Summer", "Korogocho"] },
      { name: "Embakasi South", wards: ["Imara Daima", "Kwa Njenga", "Kwa Reuben", "Pipeline", "Kware"] },
      { name: "Embakasi North", wards: ["Kariobangi North", "Dandora Area I", "Dandora Area II", "Dandora Area III", "Dandora Area IV"] },
      { name: "Embakasi Central", wards: ["Kayole North", "Kayole Central", "Kayole South", "Komarock", "Matopeni/Spring Valley"] },
      { name: "Embakasi East", wards: ["Upper Savannah", "Lower Savannah", "Embakasi", "Utawala", "Mihango"] },
      { name: "Embakasi West", wards: ["Umoja I", "Umoja II", "Mowlem", "Kariobangi South"] },
      { name: "Makadara", wards: ["Maringo/Hamza", "Viwandani", "Harambee", "Makongeni"] },
      { name: "Kamukunji", wards: ["Pumwani", "Eastleigh North", "Eastleigh South", "Airbase", "California"] },
      { name: "Starehe", wards: ["Nairobi Central", "Ngara", "Pangani", "Ziwani/Kariokor", "Landimawe", "Nairobi South"] },
      { name: "Mathare", wards: ["Hospital", "Mabatini", "Huruma", "Ngei", "Mlango Kubwa", "Kiamaiko"] },
    ],
  },
];
  